connector.name=iceberg
iceberg.catalog.type=glue
hive.metastore.glue.region=us-east-1
hive.metastore.glue.default-warehouse-dir=s3://lakehouse-hybrid-174029311478-us-east-1-warehouse/warehouse
fs.native-s3.enabled=true
s3.region=us-east-1
